.github/workflows/cd.yml, .github/workflows/ci.yml, package.json
**Description of changes made (Required)**
improvements to cicd
**Associated issue number/tracking link (Required)**
fixes #43
=> fix(cicd): add momentum design tokens branch update post merge

.github/workflows/cd.yml, .github/workflows/ci.yml
**Description of changes made (Required)**
fix default branch
**Associated issue number/tracking link (Required)**
=> Default branch

.github/workflows/cd.yml
**Description of changes made (Required)**
**Associated issue number/tracking link (Required)**
=> fix(cd): try fetch

.github/workflows/ci.yml, .github/workflows/publish.yml
yml file was incorrect
*Description of the changes made in this Pull Request*
***required***
*Links to resources related to this Pull Request*
=> fix(actions): quickfix yml

.github/workflows/publish.yml
i really wish I could test actions locally
=> fix(yml): remove ci reusable run for publish action

.github/workflows/publish.yml
***required***
*Description of the changes made in this Pull Request*
***required***
*Links to resources related to this Pull Request*
=> fix(publish): fix publish job name

packages/@momentum-design/fonts/package.json, packages/@momentum-design/icons/package.json, packages/@momentum-design/illustrations/package.json, packages/@momentum-design/token-builder/package.json
make packages private to publish
=> feat(pkg): private packages

.github/workflows/publish.yml
The scope of the changes in this pull request are to fix the publish flow, as it was missing a checkout and install.
=> fix(cd): publish flow

packages/@momentum-design/tokens/package.json
The scope of the changes in this Pull Request are to add public access to the nested package. This is explicitly for `@momentum-design/tokens`.
=> ci(tokens): add public flag

packages/@cisco-momentum/tokens/package.json
This pull request insights the release of version `0.0.1` of the tokens project.
=> feat(tokens): version bump to 0.0.1

CODE_OF_CONDUCT.md
***required***
*Description of the changes made in this Pull Request*
***required***
*Links to resources related to this Pull Request*
=> feat(conduct): add code of conduct

SECURITY.md
***required***
*Description of the changes made in this Pull Request*
***required***
*Links to resources related to this Pull Request*
=> feat(md): add security policy

.github/workflows/publish.yml, README.md, packages/@cisco-momentum/tokens/README.md, packages/@cisco-momentum/tokens/package.json, yarn.lock
The scope of the changes in this pull request are to add `semantic-release` and `semantic-release-monorepo` to the list of dependencies available, and amend the associated flows to our existing `tokens` package.
=> feat: add semantic release

.github/workflows/deploy-package.yml, .github/workflows/pull-request.yml
Hotfix for adding stable node configuration information.
=> fix(automation): node configuration

.github/workflows/pull-request.yml
Updating matrix for platforms to only run ubuntu through automation.
=> fix(automation): only run ubuntu

.github/workflows/pull-request.yml
Hotfix for automation echo quotes.
=> fix(automation): echo quotes

.github/workflows/pull-request.yml
Hotfix for package matrix in automation, updating dependencies.
=> fix(automation): package matrix dependencies

.github/workflows/pull-request.yml
Hotfix for adding a list of generated packages to automation.
=> feat(automation): display generated packages

.github/workflows/pull-request.yml
Hotfix for target branch during matrix generation in automation.
=> fix(automation): matrix checkout branch

.github/workflows/pull-request.yml
Hotfix automation matrix git branch sync.
=> fix(automaton): update branch before package sync

.github/workflows/pull-request.yml, scripts/packages.js
Hotfix for target refs in automation.
=> fix(automation): target refs

.github/workflows/pull-request.yml
Hotfix for automation: pull request job names for matrix.
=> fix(automation): pull request job names

.github/workflows/deploy-package.yml
Hotfix for adding the npm token to the publish flow for automation.
=> fix(automation): npm token for publishing

.github/workflows/deploy-package.yml
Hotfix for setting scoped npmjs tokens within automation flows.
=> fix(automation): npmjs token scoping

.github/workflows/deploy-package.yml
Hotfix for npmjs token scope exports issue.
=> fix(automation): npm js token exports issue

.github/workflows/pull-request.yml, package.json, scripts/git.js, scripts/packages.js, scripts/utils.js
The scope of the changes in this pull request are to clean the package scopes to better appear within CI/CD and other automation flows.
This pull request also includes additional flows needed to version bump various packages.
=> feat(automation): package scope cleaning

.github/workflows/deploy-package.yml
=> fix(automation): npm token single line

.github/workflows/deploy-package.yml, .github/workflows/pull-request.yml
The scope of the changes in this pull request are to fix adding changes to the version bumping.
=> fix(automation): push flow on deploy

.github/workflows/deploy-package.yml
The scope of the changes in this pull request are to fix the deploy target for changes to github via automation.
=> fix(automation): deploy target github

packages/@cisco-momentum/tokens/README.md
=> test: version bump 0

.github/workflows/deploy-package.yml, packages/@cisco-momentum/automation/src/models/index.ts, packages/@cisco-momentum/automation/src/models/package/index.ts, packages/@cisco-momentum/automation/src/models/package/package.ts, packages/@cisco-momentum/automation/src/models/package/types.ts, packages/@cisco-momentum/automation/src/utils/yarn/yarn.ts, packages/@cisco-momentum/tokens/README.md
The scope of the changes in this pull request are to remove github flows from automation on publish.
=> fix(automation): no pushing to git on publish

.eslintrc.cjs, packages/@momentum-design/token-builder/src/common/constants.ts, packages/@momentum-design/token-builder/src/common/index.ts, packages/@momentum-design/token-builder/src/common/types.ts, packages/@momentum-design/token-builder/src/models/dictionary/dictionary.ts, packages/@momentum-design/token-builder/src/models/dictionary/types.ts, packages/@momentum-design/token-builder/src/models/platform/platform.ts, packages/@momentum-design/token-builder/src/models/platform/types.ts, packages/@momentum-design/token-builder/src/models/token-builder/token-builder.ts, packages/@momentum-design/token-builder/src/transforms/elevation/constants.ts, packages/@momentum-design/token-builder/src/transforms/elevation/elevation.ts, packages/@momentum-design/token-builder/src/transforms/elevation/index.ts, packages/@momentum-design/token-builder/src/transforms/elevation/types.ts, packages/@momentum-design/token-builder/src/transforms/index.ts, packages/@momentum-design/tokens/config/tokens/core.json
The scope of the changes in this pull request are to add basic support of custom transforms to the `token-builder` package.
=> feat: allow custom token transforms

package.json, packages/@momentum-design/tokens/src/theme/webex/light.json
=> fix(tokens): light theme

packages/@momentum-design/tokens/package.json
***required*** - *Description of the changes made in this Pull Request*
=> Design token updates

packages/@momentum-design/token-builder/src/common/types.ts, packages/@momentum-design/token-builder/src/models/file/file.ts, packages/@momentum-design/token-builder/src/models/file/types.ts, packages/@momentum-design/token-builder/src/models/platform/platform.ts, packages/@momentum-design/token-builder/tsconfig.json, packages/@momentum-design/tokens/config/tokens/core.json
The scope of the changes in this pull request are to allow for the `token-builder` to support selectors within the CSS/SCSS output.
=> feat(token-builder): support selectors in output

packages/@momentum-design/token-builder/src/common/constants.ts, packages/@momentum-design/tokens/config/tokens/core.json
Add swift and android resource formats
=> feat(formats): add android and swift outputs

packages/@momentum-design/token-builder/src/schemas/json/color.json, packages/@momentum-design/tokens/src/core/color.json, packages/@momentum-design/tokens/src/theme/webex/common.json, packages/@momentum-design/tokens/src/theme/webex/dark.json, packages/@momentum-design/tokens/src/theme/webex/light.json
Schema update because I can't push directly to upstream design branch for some reason
=> Fix schema for claire

.github/workflows/deploy-package.yml, packages/@momentum-design/automation/src/commands/create-release/constants.ts, packages/@momentum-design/automation/src/commands/create-release/create-release.ts, packages/@momentum-design/automation/src/commands/create-release/index.ts, packages/@momentum-design/automation/src/commands/create-release/types.ts, packages/@momentum-design/automation/src/commands/dispatch-telemetry/index.ts, packages/@momentum-design/automation/src/commands/main/constants.ts, packages/@momentum-design/automation/src/commands/main/main.ts, packages/@momentum-design/automation/src/utils/git/constants.ts, packages/@momentum-design/automation/src/utils/git/git.test.ts, packages/@momentum-design/automation/src/utils/git/git.ts
***required*** - *Description of the changes made in this Pull Request*
=> WIP: feat(changelog): releases changelog

packages/@momentum-design/tokens/src/theme/webex/dark.json, packages/@momentum-design/tokens/src/theme/webex/light.json
• Fixed incorrect HEX Values and descriptions for decorative borders and gradient dividers for the Dark and Light themes. Waiting for the review :)
=> Theme Token Update

packages/@momentum-design/tokens/src/theme/webex/common.json, packages/@momentum-design/tokens/src/theme/webex/dark.json, packages/@momentum-design/tokens/src/theme/webex/light.json
- Corrected typos in common (text.positive)
- Fixed incorrect hex value for button primary and secondary in dark & light
- Added indicators in dark & light
- Added surface tokens in common for whiteboard component
=> Theme token change

packages/@momentum-design/icons/package.json
The scope of the changes in this Pull Request are to init the initial publish of the `icons` package.
=> feat(icons): initial publish flag

packages/@momentum-design/tokens/config/tokens/core.json
The scope of the changes in this PR are to add a CSS selector for `tokens/css` core styles.
=> feat(tokens): add core css selector

packages/@momentum-design/token-builder/src/schemas/json/common.json, packages/@momentum-design/token-builder/src/schemas/json/dark.json, packages/@momentum-design/token-builder/src/schemas/json/light.json, packages/@momentum-design/tokens/src/core/border-radius.json, packages/@momentum-design/tokens/src/theme/webex/common.json, packages/@momentum-design/tokens/src/theme/webex/dark.json, packages/@momentum-design/tokens/src/theme/webex/light.json
Theme & common token updates
- Moved 9 Illustration colors into common tokens as they have the same value.
- Moved illustration under "content" tokens. 
- Fixed some descriptions for consistency between dark & light modes. 
Ready for review ;)
=> Theme token updates

packages/@momentum-design/tokens/config/tokens/core.json, packages/@momentum-design/tokens/src/$metadata.json, packages/@momentum-design/tokens/src/stable/theme/stable-common.json, packages/@momentum-design/tokens/src/stable/theme/stable-dark.json, packages/@momentum-design/tokens/src/stable/theme/stable-light.json
Adding stable theme tokens to be able to automatically update them from Figma. 
=> feat(tokens): add current theme tokens

packages/@momentum-design/tokens/src/stable/theme/stable-common.json, packages/@momentum-design/tokens/src/stable/theme/stable-dark.json, packages/@momentum-design/tokens/src/stable/theme/stable-light.json
=> feat(tokens): fix stable tokens

packages/@momentum-design/tokens/config/tokens/core.json
The scope of the changes in this pull request are to change the tokens css output selector from `md` to `mds`.
=> fix(tokens): css selector md to mds

packages/@momentum-design/docs/src/components/IconTable/IconTable.css, packages/@momentum-design/docs/src/pages/en/docs/api-reference/[...slug].astro, packages/@momentum-design/docs/src/styles/theme.css
- fix urls to not have .md in the folder names.
- fix icons tooltip to show name correctly
- fix icons color for light theme
=> feat(docs): fix urls

.github/workflows/deploy-package.yml, .github/workflows/docs.yml, .github/workflows/pull-request.yml
related to: https://github.com/momentum-design/momentum-design/pull/412
=> Cache dep issue try2

packages/@momentum-design/icons/config/momentum.json
- Rename of the icons swift file to match requirements
=> fix(icons): icons swift file rename

packages/@momentum-design/icons/config/templates/momentum.swift.hbs
=> fix: swift unhandled case

packages/@momentum-design/figma-plugin-assets-export/.eslintrc.cjs, packages/@momentum-design/figma-plugin-assets-export/src/ui/components/Button/Button.test.tsx, packages/@momentum-design/figma-plugin-assets-export/src/ui/components/Footer/Footer.test.tsx, packages/@momentum-design/figma-plugin-assets-export/src/ui/components/Footer/Footer.tsx, packages/@momentum-design/figma-plugin-assets-export/src/ui/components/Help/Help.test.tsx, packages/@momentum-design/figma-plugin-assets-export/src/ui/components/Help/Help.tsx, packages/@momentum-design/figma-plugin-assets-export/src/ui/components/Link/Link.test.tsx, packages/@momentum-design/figma-plugin-assets-export/src/ui/components/List/List.test.tsx, packages/@momentum-design/figma-plugin-assets-export/src/ui/components/List/List.tsx, packages/@momentum-design/figma-plugin-assets-export/src/ui/components/Row/Row.test.tsx, packages/@momentum-design/figma-plugin-assets-export/src/ui/components/Row/Row.tsx, packages/@momentum-design/figma-plugin-assets-export/src/ui/components/SectionHeader/SectionHeader.test.tsx, packages/@momentum-design/figma-plugin-assets-export/src/ui/components/SectionHeader/SectionHeader.tsx, packages/@momentum-design/figma-plugin-assets-export/src/ui/components/Select/Option.test.tsx, packages/@momentum-design/figma-plugin-assets-export/src/ui/components/Select/Select.test.tsx, packages/@momentum-design/figma-plugin-assets-export/src/ui/components/Tabs/Tab.test.tsx, packages/@momentum-design/figma-plugin-assets-export/src/ui/components/Tabs/Tabs.test.tsx, packages/@momentum-design/figma-plugin-assets-export/src/ui/components/TextArea/TextArea.test.tsx, packages/@momentum-design/figma-plugin-assets-export/src/ui/components/TextInput/TextInput.test.tsx
figma-plugin-assets-export
ui folder test cases
=> test: test cases for figma ui files

packages/@momentum-design/builder/src/assets/builder/file-handler.ts
window icons package build issue fixed.
=> window icons package build issue fixed

.github/workflows/deploy-package.yml, packages/@momentum-design/automation/src/commands/create-release/create-release.ts, packages/@momentum-design/automation/src/utils/git/git.test.ts, packages/@momentum-design/automation/src/utils/git/git.ts
Implementation of the version history
=> Implementation of the version history

package.json, packages/@momentum-design/brand-visuals/.eslintrc.js, packages/@momentum-design/brand-visuals/LICENSE.md, packages/@momentum-design/brand-visuals/README.md, packages/@momentum-design/brand-visuals/SCRIPTS.md, packages/@momentum-design/brand-visuals/package.json, yarn.lock
created new repo brand-visuals
=> Create new brand visuals repo

packages/@momentum-design/figma-plugin-assets-export/config/figma-plugin-settings-default.json
- Added Figma-plugin-default-settings as a reference
=> docs: added figma-plugin-default-settings

packages/@momentum-design/icons/src/brand/cisco-ai-assistant.svg
feat(assets): Asset Automation 2024-02-14T17:18:28.326Z
=> Asset Automation 2024-02-14T17:18:28.326Z

.eslintrc.js
linebreak Lf Crlf changes for windows
=> feat: linebreak lf crlf changes for windows

packages/@momentum-design/figma-plugin-assets-export/config/figma-plugin-settings-default.json
Figma Plugin / Create new config for Assets repo
=> feat: added new export config for brand visuals

packages/@momentum-design/figma-plugin-assets-export/src/ui/components/Hint/Hint.css, packages/@momentum-design/figma-plugin-assets-export/src/ui/components/Hint/Hint.tsx, packages/@momentum-design/figma-plugin-assets-export/src/ui/components/Link/Link.css, packages/@momentum-design/figma-plugin-assets-export/src/ui/components/Link/Link.tsx, packages/@momentum-design/figma-plugin-assets-export/src/ui/sections/export/Export.css, packages/@momentum-design/figma-plugin-assets-export/src/ui/sections/export/Export.tsx
Bug / Assets Export Description Styling
=> fix: css alignment issue fix

CONSUMPTION.md, README.md, packages/@momentum-design/automation/src/commands/create-release/constants.ts
- Fix the create-release constants to include brand-visuals in release history
- Updated docs with Brand visuals
=> fix: brand-visuals release and docs

packages/@momentum-design/automation/src/commands/create-release/create-release.ts
git release history title/subject issue fixed.
=> fix: git release title fixed

packages/@momentum-design/tokens/config/tokens/core.json
- Fix the tokens config to include the high contrast theme tokens in the dist
With this change high contrast theme tokens are now available for consumption.
=> fix(tokens): tokens config to include high contrast themes

.vscode/settings.json, CONTRIBUTING.md
- Added to the contribution guide of the repo, to allow for contributions and provide more information
- Added VS Code settings to make sure fixlint is executed on save.
=> docs(root): added to contribution guide

packages/@momentum-design/icons/config/momentum.json
Update relative path to MomentumFontIcons WOFF files
=> refactor: update path to woff file

.github/workflows/pull-request.yml, packages/@momentum-design/components/README.md
- Try to fix the components post build
=> fix: components post build

.github/workflows/deploy-package.yml, .github/workflows/pull-request.yml
- Github actions install and caching changes to make sure it works as expected across yarn workspaces
=> fix(ci): github actions install and caching properly

CONTRIBUTING.md, packages/@momentum-design/components/README.md
- Add steps to contribute `@momentum-design/components` package.
=> feat(md): add steps to contribute for components pkg

.github/workflows/docs.yml, .github/workflows/pull-request.yml, packages/@momentum-design/automation/package.json, packages/@momentum-design/automation/src/utils/compression/compression.ts, packages/@momentum-design/docs/src/config.ts, packages/@momentum-design/docs/src/env.d.ts, yarn.lock
***required*** - *Description of the changes made in this Pull Request*
=> feat(tar): fix import

packages/@momentum-design/docs/src/components/IconTable/IconTable.tsx, packages/@momentum-design/docs/src/components/IllustrationTable/IllustrationTable.tsx
Revert icons and illustrations final path
=> fix: revert icons and illustrations final path

packages/@momentum-design/docs/astro.config.mjs
Updated icons and illustrations src path with with better approach
=> fix: code clean of icons and illustrations src path

.github/workflows/pull-request.yml
- Run initialize and analyze root steps in parallel
- Cleanup of CI
=> ci: run initialize and analyze root in parallel

.github/workflows/pull-request.yml
- Cleanup PR workflow for CI by moving the build to a different spot
- Removing unnecessary matrix configs
- This has no impact to outputs, i.e. assets like icons, tokens, illustrations
=> ci: cleanup pull request workflow

.github/workflows/pull-request.yml
- Fix generate package matrix by building telemetry before automation
- This has no impact on consumables
=> ci: fix generate package matrix

.github/workflows/deploy-package.yml, .github/workflows/docs.yml, .github/workflows/pull-request.yml
- Yarn is running more often than its actually needed, removing it from ci
- Cleanup some v2 of cache/checkout
=> ci: remove duplicated yarn

.github/workflows/pull-request.yml
- Cache telemetry dist is not stable against changes in PRs, thus switching it to caching whole dist
=> fix: ci-cache-telemetry

packages/assets/tokens/src/core/value.json
[highcontrast]
Updated system colors in description. Fixed the typo for following: 
- color.highcontrast.black.SystemColorWindowTextColor 
- color.highcontrast.black.SystemColorHotlightColor
=> Highcontrast Token (09/04/2024) - core token

.github/mergeable.yml
- Adding the first iteration of mergeable bot, to check for correct PR titles, automatically add label etc.
- This change does not have any impact for consumables
=> ci: first iteration mergeable

.github/mergeable.yml
- Fix mergeable config by adding empty validate
- This doesn't have an affect on any consumables
=> ci: mergeable-config-empty-validate

.github/mergeable.yml
- More mergeable changes to add labels based on changes
- Improved title regex to allow for titlecase
=> ci: mergeable-more-changes

.github/mergeable.yml
- Fix YAML format of mergeable
=> fix: mergeable-invalid-yaml

packages/assets/fonts/README.md, packages/assets/fonts/package.json
* Update files field
* Update docs for font 
https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-272
=> build: update package files field and update docs

.github/mergeable.yml
- Making sure we add more labels to determine where changes are made
- Cleanup of existing setup to always make sure labels are set as expected
=> ci: added labels to mergeable

.github/mergeable.yml
- Mergeable runs too often now, causing issues - changing the events to just a subset where it should actually run
=> ci: fix mergeable events

.github/mergeable.yml
- Removed edited event from labels, in mergeable
=> ci: mergeable-fix-label-edited-event

packages/components/package.json
* Update package.json main, types and exports to the correct directory
=> build: update components package.json exports

.github/mergeable.yml
- Fix mergeable by running on PR review as well
=> ci: fix-mergeable-run-on-pr-review

CONSUMPTION.md, README.md
- Added the new packages to the general README and Consumption guide
=> docs: updated general readme

packages/tools/automation/src/commands/get-packages/constants.ts, packages/tools/automation/src/commands/increment-packages/constants.ts, packages/tools/automation/src/commands/increment-packages/increment-packages.ts, packages/tools/automation/src/commands/increment-packages/increment-packages.unit.test.ts, packages/tools/automation/src/commands/increment-packages/types.ts, packages/tools/automation/src/models/fixtures/packages.fixture.ts, packages/tools/automation/src/models/package/package.ts, packages/tools/automation/src/utils/git/git.test.ts, packages/tools/automation/src/utils/git/git.ts
- This PR contains modifications to the @momentum-design/automation package to handle semantic versioning.
- When a pull request (PR) includes the prefix feat, the associated packages will be incremented by a minor version. For all other cases, a patch update will be applied.
- [MOMENTUM-264](https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-264)
=> feat: automation semantic versioning

.github/workflows/deploy-package.yml
- Fix deploy, increment packages
=> ci: fix deploy increment packages

.github/workflows/pull-request.yml, packages/components/package.json
- Add test:e2e:install to package.json to support browsers install on workflow CI.
=> test(e2e): add playwright install to support browser install on CI

packages/components/package.json
- Add scripts to support e2e test for each browser 
- Support install microsoft edge for playwright
=> test(e2etest): add scripts to support e2e test for each browser

packages/components/src/components/themeprovider/themeprovider.stories.ts, packages/components/src/components/themeprovider/themeprovider.styles.ts
The Themeprovider component is now ready for consumption and considered stable.
See more details in [Storybook](https://momentum-design.github.io/momentum-design/en/components/).
There are outstanding small changes, like using the new Typography tokens, which will be reflected in Patch Versions.
=> feat: themeprovider release

packages/components/src/components/themeprovider/themeprovider.styles.ts
- Fix the postbuild failed, it cause by the comment in the css.
=> test(e2etest): fix e2e failed issue

.github/pull_request_template.md
- Updated Github pull request template to provide more information when opening a PR.
Note: since the majority is in a "comment" (using `<!--`), it will not be a problem when creating PRs. 
How it will look like when creating a PR:
=> chore: updated github pr template

packages/components/conventions/component-aria-delegation.md
- Added convention for Aria Delegation vs Host Aria
=> docs: convention for aria delegation

packages/components/conventions/component-tsdoc.md
- Added convention for Component TSDoc
=> docs: added convention for tsdoc

packages/tools/automation/src/commands/create-release/constants.ts
- The create release command currently didn't create releases for certain packages. This PR fixes this.
- This is a pure CI change, no impact to output.
- Releases of the added packages should now also start to appear in the release history.
=> ci: fix automation targets

packages/components/src/components/iconprovider/iconprovider.component.ts, packages/components/src/components/iconprovider/iconprovider.stories.ts, packages/components/src/components/text/text.component.ts, packages/components/src/components/text/text.constants.ts, packages/components/src/components/text/text.stories.ts, packages/components/src/components/themeprovider/themeprovider.component.ts, packages/components/src/components/themeprovider/themeprovider.stories.ts, packages/components/src/tsdoc.json
- Cleanup of constants and switch
- Adding cssPart to tsdoc and added it to Text TSDoc
- Cleaned up default slots to not say "default", cause it can be confused to be a "named" slot
=> refactor: small changes to text component

packages/components/conventions/component-tsdoc.md, packages/components/src/tsdoc.json
Updated the convention docs for tsdoc to support a few more properties.
=> docs: updated tsdoc to support few more properties

packages/components/config/playwright/playwright.config.ts
Since the PR https://github.com/momentum-design/momentum-design/pull/884 got merged, the postbuild is failing.
_Please replace this line with relevant links to the changes made in this Pull Request._
=> fix: update playwright config test command

packages/components/config/playwright/docker/playwright.docker.config.ts
This PR is continuation of the previous https://github.com/momentum-design/momentum-design/pull/919 PR.
This will help fix the playwright config in docker.
=> fix: update playwright config test command in docker

packages/tools/token-builder/src/common/constants.ts
In order to support focus ring related tokens with appropriate format, add ts/color/modifiers. This transforms color modifiers from Tokens Studio to color values.
=> fix: add color modifiers to convert color tokens from Tokens Studio to color values.

CONTRIBUTING.md, packages/components/conventions/clean-code-guidelines.md, packages/components/conventions/component-code-structure.md, packages/components/conventions/component-color-tokens.md, packages/components/conventions/component-css-rem-unit.md, packages/components/conventions/component-import.md, packages/components/conventions/constants-and-enums.md, packages/components/conventions/typescript-type-only-imports.md
Creating a list of convention documents that can be considered as guidelines while building our components.
[MOMENTUM-385](https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-385)
=> docs: created a set of convention documentations

packages/components/src/components/presence/presence.component.ts
- Update strings in the component with constants.
- This will help reduce the risk of updating the fixed values of both type and size properties.
- NA
=> chore: update strings with consts in prescence component

packages/components/config/storybook/main.js, packages/components/config/storybook/preview.js, packages/components/package.json, yarn.lock
Add RTL addon which allows you to switch to right-to-left flow in your stories in Storybook.
https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-417
=> fix: add rtl addon in storybook

packages/documentation/src/components/TokenCard/TokenCardWrapper.astro, packages/documentation/src/pages/en/tokens/[tokenType].astro
Show the new typography tokens on our Astro Docs page, under Design Tokens.
https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-369
=> docs: add typography button in astro docs

packages/components/config/plop/templates/add/component/{{componentName}}.e2e-test.ts.hbs, packages/components/config/plop/templates/add/component/{{componentName}}.stories.ts.hbs, packages/components/config/storybook/preview.js
- This issue has arisen since this [commit](https://github.com/momentum-design/momentum-design/commit/76c2a99bae59121e1792ef5ccc79056e9c401001), and this pull request addresses the fixes.
- 
https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-423
=> fix: storybook setup for new components

packages/components/conventions/component-error-handling.md
- Added new Convention to components package for proper Error Handling
=> docs: error handling convention

packages/components/src/components/icon/icon.styles.ts, packages/components/src/components/icon/icon.utils.ts
- Added part to the Icon CSS to be able to style it and assert better during testing.
=> fix: added part to icon css

packages/components/src/Consumption.mdx
- Added a section about styling overrides in the consumption guide
Note: no changes to output
=> docs: consumption guide styling

packages/components/src/components/button/button.stories.ts
Updating the storybook status to release button component.
https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-389
=> feat: publish button component

packages/components/src/components/avatar/avatar.stories.ts
- Updating the storybook status to release avatar component.
- https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-421
=> feat: complete and release avatar component

packages/components/src/components/avatar/avatar.stories.ts
=> fix: release avatar component

packages/components/src/components/bullet/bullet.stories.ts, packages/components/src/components/divider/divider.stories.ts, packages/components/src/components/marker/marker.stories.ts
Release Decorator component that includes:
1] Bullet
2] Divider
3] Marker
https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-460
=> feat: release decorator component

packages/components/conventions/component-import.md, packages/components/conventions/data-attributes-on-host.md
Updated conventions to add:
1. Update the conventions to use data attributes on the host instead of adding class names.
2. Convention to use Tagnames by importing from existing components instead of creating hard coded constant values.
https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-462
=> docs: conventions for components

packages/components/conventions/data-attributes-on-host.md, packages/components/src/Consumption.mdx
Fixing a few typography issues on documentations.
=> fix: typo mistakes are fixed

packages/components/src/components/button/button.component.ts, packages/components/src/components/buttonsimple/buttonsimple.component.ts
- Documentation changes to button and button simple component w.r.t sizing.
=> fix: updated documentation for button component

packages/components/src/components/avatarbutton/avatarbutton.stories.ts
- Release Avatarbutton component.
- https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-464
=> feat: release avatar button component

packages/components/config/plop/templates/add/component/{{componentName}}.types.ts.hbs, packages/components/src/components/button/button.component.ts, packages/components/src/components/buttonsimple/buttonsimple.component.ts, packages/components/src/utils/mixins/DisabledMixin.ts, packages/components/src/utils/mixins/TabIndexMixin.ts
- This PR adds a new file `{{componentName}}.types.ts.hbs` to the plop script generator for new components.
- This PR refactors buttonSimple and button component to use DisableMixin and TabIndexMixin.
=> refactor: plop script; using mixins on button

packages/components/src/components/icon/icon.component.ts, packages/components/src/components/icon/icon.e2e-test.ts, packages/components/src/components/icon/icon.styles.ts
1. Created a CSS variable to store the dynamically computed size value.
2. Used the CSS variable to set the height and width properties in the relevant classes.
https://github.com/user-attachments/assets/5ffafbff-8704-4878-8723-23e8f3749d0f
https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-408
=> refactor: added css variable to update size through classes

packages/components/src/utils/mixins/LabelMixin.ts
This label mixin would be reused within input, checkbox, radio and select components.
=> chore: created mixin for label

packages/documentation/astro.config.mjs, packages/documentation/src/components/BrandVisualsTable/BrandVisualsTable.css, packages/documentation/src/components/BrandVisualsTable/BrandVisualsTable.tsx, packages/documentation/src/components/IconTable/IconTable.css, packages/documentation/src/components/IconTable/IconTable.tsx, packages/documentation/src/components/IllustrationTable/IllustrationTable.css, packages/documentation/src/components/IllustrationTable/IllustrationTable.tsx, packages/documentation/src/pages/en/assets/index.mdx, packages/documentation/src/pages/en/tokens/brand-visuals.mdx, packages/documentation/src/styles/theme.css
- Added Brand Visuals to Assets page, including Brand visuals browser and logic to display the right background color depending on the brand visual.
- Removed "Download" button from tooltips, since manual download should not happen.
=> docs: added brand visuals

packages/tools/figma-plugins/assets-export/config/figma-plugin-settings-default.json
- Edited Figma plugin assets export settings for splitting illustrations into separate folders
- Create placeholders to move illustrations into folders
- Placeholders will be removed once illustrations moved
=> fix: illustrations moving to separate folders

packages/tools/figma-plugins/assets-export/config/figma-plugin-settings-default.json, packages/tools/figma-plugins/assets-export/src/shared/settings-constants.ts, packages/tools/figma-plugins/assets-export/src/shared/types.ts, packages/tools/figma-plugins/assets-export/src/ui/models/github.ts
- Updated the Figma Plugin such that we can now add the validated label directly through the plugin - less work and problems when using the plugin.
- Updated the config for illustrations to actually make it work.
=> fix: figma plugin adding labels and updated config

packages/assets/brand-visuals/README.md
Updated the submission and consumption guidelines for the brand visuals read.me.
=> docs: updated brand visuals readme.md

packages/components/src/components/toggle/toggle.stories.ts
Release Toggle component
https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-513
=> feat: release toggle component

packages/components/src/components/input/input.stories.ts
Releasing input component for consumption.
https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-483
=> feat: releasing input component

packages/components/src/components/radio/radio.stories.ts
-  Release radio component.
- [Figma](https://www.figma.com/design/MrrkzCQ0YXzUTca2XhesDZ/%F0%9F%93%9C-%5BWIP%5D-Momentum-Web-Library-Documentation-2.0---v1.0?node-id=1533-71223&m=dev)
- [Epic link](https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-310)
=> feat: release radio component

packages/components/config/storybook/preview.js, packages/components/src/Consumption.mdx, packages/components/src/components/buttonsimple/buttonsimple.stories.ts, packages/components/src/components/formfieldwrapper/formfieldwrapper.stories.ts, packages/components/src/components/input/input.component.ts, packages/components/src/components/input/input.stories.ts, packages/components/src/components/modalcontainer/modalcontainer.stories.ts
Updated input component and consumption guide.
https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-528
=> docs: input component and updated consumption guide

packages/components/src/components/checkbox/checkbox.component.ts, packages/components/src/components/checkboxgroup/checkboxgroup.component.ts, packages/components/src/components/checkboxgroup/checkboxgroup.constants.ts, packages/components/src/components/checkboxgroup/checkboxgroup.e2e-test.ts, packages/components/src/components/checkboxgroup/checkboxgroup.stories.ts, packages/components/src/components/checkboxgroup/checkboxgroup.styles.ts, packages/components/src/components/checkboxgroup/checkboxgroup.types.ts, packages/components/src/components/checkboxgroup/index.ts, packages/components/src/index.ts
- Add checkbox group component.
- Nested & Parent level code branch is located here [checkbox-nested-branch](https://github.com/arjunkesava/momentum-design/tree/checkbox-nested-branch)
-
=> chore: build checkbox group component

packages/components/package.json
Fix update snapshot script for edge
=> fix: e2e test script for edge

packages/components/src/components/tab/tab.stories.ts
Release Tab component
[Jira ticket](https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-532)
=> feat: Publish Tab component

packages/components/src/Consumption.mdx
PR to add more information about Provider in consumption page.
[Docs / Improve IconProvider documentation](https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-541)
=> docs: consumption guide updated for Providers

packages/components/src/components/button/button.component.ts, packages/components/src/components/button/button.stories.ts
Trimming empty spaces from button to infer the correct button type - pill, icon, pill with icon
=> fix: trim white space and empty spaces

packages/components/src/components/radiogroup/radiogroup.stories.ts
Release radio component.
[Epic](https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-317)
[Figma](https://www.figma.com/design/MrrkzCQ0YXzUTca2XhesDZ/%F0%9F%93%9C-%5BWIP%5D-Momentum-Web-Library-Documentation-2.0---v1.0?node-id=1-37&p=f&m=dev)
=> feat: release radiogroup component

packages/components/src/components/input/input.component.ts, packages/components/src/components/input/input.styles.ts
* Updated styles on focus
* Added support to aria-invalid on error validation type
https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-566
=> style: helptexttype on input focus

packages/components/src/components/list/index.ts, packages/components/src/components/list/list.component.ts, packages/components/src/components/list/list.constants.ts, packages/components/src/components/list/list.e2e-test.ts, packages/components/src/components/list/list.stories.ts, packages/components/src/components/list/list.styles.ts, packages/components/src/components/listitem/index.ts, packages/components/src/components/listitem/listitem.component.ts, packages/components/src/components/listitem/listitem.constants.ts, packages/components/src/components/listitem/listitem.e2e-test.ts, packages/components/src/components/listitem/listitem.stories.ts, packages/components/src/components/listitem/listitem.styles.ts, packages/components/src/components/listitem/listitem.types.ts, packages/components/src/index.ts
- Add list component.
- Add listitem component, with slots and label text.
- Figma:  https://www.figma.com/design/MrrkzCQ0YXzUTca2XhesDZ/%F0%9F%93%9C-%5BWIP%5D-Momentum-Web-Library-Documentation-2.0---v1.0?node-id=1-31
=> perf: build list and listitem components

packages/components/src/components/checkbox/checkbox.component.ts, packages/components/src/components/input/input.component.ts, packages/components/src/components/radio/radio.component.ts, packages/components/src/components/toggle/toggle.component.ts, packages/components/src/utils/mixins/FormInternalsMixin.ts
Updated the mixin to remove generating random id and setting it on the attribute
Updated individual components to do the same.
https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-567-
=> refactor: random generation of id added individually

packages/components/src/components/popover/popover.component.ts
- these 2 properties need to be attributes & reflective so they can be used externally
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-629057
https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-584
=> fix(popover): make id and triggerid reflective

packages/components/src/index.ts
export the placement type so it can be used in mrv2
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-629057
https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-584
=> fix(coachmark): export placement type

packages/documentation/astro.config.mjs, packages/documentation/src/components/Tokens/TokenTable/TokenTable.tsx
- Currently logos are not showing up on the docs page due to recent restructuring of folders, this will fix it.
This is purely a change for the documentation page.
=> docs: brand visuals folder restructuring fix

packages/components/src/components/progressbar/progressbar.stories.ts
Release Progressbar component
https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-586
=> feat: release progressbar component

packages/components/src/components/searchfield/searchfield.stories.ts
Releasing searchfield component
https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-595
=> feat: releasing searchfield component

packages/components/src/components/buttonlink/buttonlink.stories.ts
=> feat: release ButtonLink component

packages/components/src/components/staticcheckbox/staticcheckbox.stories.ts, packages/components/src/components/staticradio/staticradio.stories.ts, packages/components/src/components/tablist/tablist.stories.ts
* Releasing tablist component
* Updating static radio and checkbox component badges on storybook
=> feat: release tablist component

packages/components/conventions/mixin-tsdoc-guidelines.md
Add a convention for using mixins in TypeScript to avoid issues with type inference when introducing new public or protected APIs.
=> fix: add Mixin convention to avoid TypeScript issues

packages/components/src/components/card/card.stories.ts, packages/components/src/components/cardbutton/cardbutton.stories.ts, packages/components/src/components/cardcheckbox/cardcheckbox.stories.ts, packages/components/src/components/cardradio/cardradio.stories.ts
Releasing card component
MOMENTUM-682
=> feat: release card component

packages/components/src/components/animation/animation.component.ts, packages/components/src/components/animation/animation.types.ts
add on load event to animation component
=> feat(components): add on load event to animation component

packages/tools/builder/src/assets/builder/constants.ts, packages/tools/builder/src/assets/builder/transformer/factory.ts, packages/tools/builder/src/assets/builder/transformer/manifest-js-transformer.ts, packages/tools/builder/src/assets/builder/types.ts
add manifest module transformer to builder tool
=> fix(tools): add manifest module transformer to builder tool

packages/assets/animations/config/momentum.json, packages/components/src/components/animation/animation.component.ts, packages/components/src/components/animation/animation.stories.ts, packages/components/src/components/badge/badge.e2e-test.ts
import animation manifest also fix error handling
=> fix(components): import animation manifest

packages/components/src/components/animation/animation.component.ts, packages/components/src/components/animation/animation.stories.ts
Fix animation component's type imports
And animation manifest imports
=> fix(components): animation type imports

packages/components/src/components/animation/animation.component.ts, packages/components/src/components/animation/animation.stories.ts
Fix animation manifest imports, basically roll it back to the previous implementation.
=> fix(components): animation manifest imports

packages/components/config/esbuild/esbuild-e2e.config.js, packages/components/src/components/animation/animation.component.ts
Animation data loaded directly from dist folder, but it contains other files and bundler might pick them.
Now import restricted to dist/lottie folder.
=> fix(components): animation dynamic import

packages/components/src/components/button/button.stories.ts, packages/components/src/components/buttonsimple/buttonsimple.component.ts, packages/components/src/components/buttonsimple/buttonsimple.e2e-test.ts, packages/components/src/components/toggletip/toggletip.e2e-test.ts, packages/components/src/utils/mixins/AutoFocusMixin.ts
- Added new attribute "autofocus" to ButtonSimple, Button component to allow consumers to automatically focus the Button after render.
- Added e2e test
=> fix: button autofocus mixin

packages/components/src/components/navmenuitem/navmenuitem.stories.ts, packages/components/src/components/sidenavigation/sidenavigation.stories.ts
The PR releases two components:
1] SideNavigation 
2] NavMenuItem
=> feat: release sidenavigation component

packages/components/src/components/divider/divider.stories.ts, packages/components/src/components/divider/divider.styles.ts
- Small fix to make sure the Divider text does not word wrap, but stay inline
- Updating storybook for better adjustments of the text
=> fix: divider text styling

packages/components/src/components/checkbox/checkbox.styles.ts, packages/components/src/components/popover/popover.component.ts, packages/components/src/components/select/select.styles.ts, packages/components/src/components/themeprovider/themeprovider.component.ts, packages/components/src/components/themeprovider/themeprovider.styles.ts
- [Select] Fixed issue where auto sizing wasn't considered (keeping the Select in view)
- [Themeprovider] Changed scrollbar-track to transparent color
- [Checkbox] Fixed issue where when scrolling a group of checkboxes the checkbox can't be clicked anymore
=> fix: several styling fixes

packages/components/src/components/option/option.styles.ts
[Option] - small stying adjustment to ensure it doesn't shrink in height when used in select
=> fix: small styling adjustment in option component

packages/components/src/components/accordion/accordion.component.ts, packages/components/src/components/accordion/accordion.stories.ts, packages/components/src/components/accordionbutton/accordionbutton.component.ts, packages/components/src/components/accordionbutton/accordionbutton.stories.ts, packages/components/src/components/accordiongroup/accordiongroup.component.ts, packages/components/src/components/accordiongroup/accordiongroup.stories.ts
- This PR will release the accordion components:
- Accordion
- Accordion Button
- Accordion Group
=> feat: release accordion family

packages/components/src/components/listitem/listitem.component.ts, packages/components/src/components/listitem/listitem.stories.ts, packages/components/src/components/listitem/listitem.styles.ts
- [ListItem] Adding a `content` slot to override the content of the listitem for higher flexibility. This should only be used in rare circumstances, given design specs should be followed.
- [ListItem] Added more custom css properties to enhance styling flexibility
- [ListItem] Added a story for showcasing the changes
=> fix: added customisation options to listitem

packages/components/src/components/dialog/dialog.stories.ts, packages/components/src/components/listitem/listitem.stories.ts
**Docs:**
- [ListItem] Small styling fix for ListItem story in Storybook
- [Dialog] Adding additional story for a List in Dialog in Storybook
=> docs: fix listitem and dialog stories (storybook only)

packages/components/src/components/slider/slider.stories.ts
=> feat: release slider component

packages/components/src/components/combobox/combobox.stories.ts
- Release combobox component and mark it stable.
- MOMENTUM-765
=> feat: release combobox

packages/components/src/components/list/list.component.ts, packages/components/src/components/listitem/listitem.component.ts, packages/components/src/components/select/select.component.ts, packages/components/src/components/select/select.e2e-test.ts, packages/components/src/utils/mixins/lifecycle/lifecycle.contants.ts
- [Select] - Fix an issue where disabling options wasn't considered for keyboard interaction
- [List] - Fix an issue where disabling options wasn't considered for keyboard interaction
=> fix: select & list lifecycle disabled issue

packages/components/src/docs/Attributes.mdx
This PR updates docs to clearly explain the differences between read-only, disabled, and soft-disabled states across components.
=> docs: add docs to differentiate readonly, disabled and soft-disabled

packages/tools/storybook-addon-code-preview/package.json, packages/tools/storybook-addon-code-preview/src/components/codeTransform.ts
Re-structuring the code calculate import only once.
These are only storybook changes.
=> fix(storybook): refactor imports handling in code preview

packages/components/config/storybook/provider/overrides.css, packages/components/src/docs/Consumption.mdx
- Adding documentation about webkit-font-smoothing to consumption guide.
- Updating storybook to apply webkit-font-smoothing.
**NOTE for consumers:**
If you are a consumer of the library and have not webkit-font-smoothing set to antialias on the top of the app, please enable it to match respective design specs.
=> fix: add webkit-font-smoothing

packages/components/config/storybook/preview.jsx, packages/components/config/storybook/provider/storyDescription.js, packages/components/src/components/button/button.stories.ts
Add storyDescription decorator
=> fix(storybook): render short description for stories
