.github/workflows/publish.yml
The changes within this PR are to allow CD to set the NPM_TOKEN for deploying packages.
=> fix(yarn): token abstraction

README.md, packages/@momentum-design/token-builder/README.md, packages/@momentum-design/token-builder/src/common/config-file.fixture.ts, packages/@momentum-design/token-builder/src/common/types.ts, packages/@momentum-design/token-builder/src/models/dictionary/dictionary.test.ts, packages/@momentum-design/token-builder/src/models/file/file.fixture.ts, packages/@momentum-design/token-builder/src/models/file/file.test.ts, packages/@momentum-design/token-builder/src/models/file/file.ts, packages/@momentum-design/token-builder/src/models/file/types.ts, packages/@momentum-design/token-builder/src/models/platform/platform.test.ts, packages/@momentum-design/token-builder/src/models/platform/platform.ts, packages/@momentum-design/tokens/config/tokens/webex.json
The scope of the changes in this pull request is to allow for references to be used within the `@momentum-design/token-builder` package. This allows for built tokens to render with references to their associated values, instead of having the finalized value.
=> feat(token-builder): add reference support

.github/workflows/publish.yml
The scope of the changes in this pull request are to add a build flow to the publish automation flow to make sure that all packages are built before publishing to the artifactories.
=> fix(automation): build on publish

packages/@cisco-momentum/icons/package.json, packages/@cisco-momentum/illustrations/package.json
The changes within this pull request address the invalid `build` scripts within all packages that do not currently have a `build` workflow.
=> fix: md-token-builder invalid references

.eslintrc.cjs, config/esbuild/esbuild.config.js, packages/@momentum-design/token-builder/esbuild.config.js, packages/@momentum-design/token-builder/esbuild.config.mjs, packages/@momentum-design/token-builder/jest.config.js, packages/@momentum-design/token-builder/package.json, packages/@momentum-design/token-builder/test/module/module.test.ts, packages/@momentum-design/token-builder/tsconfig.json, packages/@momentum-design/tokens/README.md, yarn.lock
The scope of the changes in this Pull Request are to make the `@momentum-design/token-builder` into a module as ESM for exporting.
=> feat(token-builder): distribute esm module

.github/workflows/deploy-package.yml
The scope of the changes in this pull request are to fix the index used when determining which changes need to be deployed. This was previously looking back one additional merge, causing it to publish packages with potentially no changes in them.
Below is from a PR that only had changes within `@momentum-design/tokens` and `@momentum-design/token-builder`. As noted, it looked back at the previous PR, which included all packages within its changes.
=> fix(automation): git index for changes on deploy

packages/@momentum-design/tokens/config/tokens/core.json
Hotfix for output file name including `json` for all formats.
=> fix(tokens): json in output file name

packages/@momentum-design/builder/esbuild.config.mjs, packages/@momentum-design/builder/package.json, packages/@momentum-design/builder/src/commands/definition/definition.ts, packages/@momentum-design/builder/src/icons/builder/builder.ts, packages/@momentum-design/builder/src/icons/builder/constants.ts, packages/@momentum-design/builder/src/icons/builder/index.ts, packages/@momentum-design/builder/src/icons/builder/types.ts, packages/@momentum-design/builder/src/icons/index.ts, packages/@momentum-design/builder/src/index.ts, packages/@momentum-design/builder/src/models/builder/builder.ts, packages/@momentum-design/builder/src/models/builder/types.ts, packages/@momentum-design/icons/config/webex.json, packages/@momentum-design/icons/package.json, yarn.lock
- Extended the builder package with icons
- Modified initialise, more to come on the process method. 
- Added config & build script to `icons` package, which will transform & optimise the `src` folder and outputs it to `dist` folder (this will be the dist we are trying to have the same as momentum-ui does for the icons)
=> feat(builder): added icons builder and icons package

packages/@momentum-design/token-builder/src/schemas/json/common.json, packages/@momentum-design/token-builder/src/schemas/json/dark.json, packages/@momentum-design/token-builder/src/schemas/json/light.json, packages/@momentum-design/tokens/src/theme/webex/common.json, packages/@momentum-design/tokens/src/theme/webex/dark.json, packages/@momentum-design/tokens/src/theme/webex/light.json
Schemas had a typo on default (using 'defualt'). Correcting it in this PR so that https://github.com/momentum-design/momentum-design/pull/160 can be testes against correct schemas.
Im only changing the theme/webex files so that the pipeline in this PR passes. But I do not intend this changes to be permanent, but overwritten by design-token-updates branch PRs
=> feat(remove-defualt): defualt typo in schemas

.github/workflows/docs.yml, packages/@momentum-design/token-builder/src/common/constants.ts, packages/@momentum-design/token-builder/src/formats/index.ts, packages/@momentum-design/token-builder/src/formats/json-minimal/constants.ts, packages/@momentum-design/token-builder/src/formats/json-minimal/index.ts, packages/@momentum-design/token-builder/src/formats/json-minimal/json-minimal.ts, packages/@momentum-design/token-builder/src/index.ts, packages/@momentum-design/token-builder/src/models/token-builder/token-builder.ts, packages/@momentum-design/token-builder/src/transforms/elevation/index.ts, packages/@momentum-design/token-builder/src/transforms/index.ts, packages/@momentum-design/tokens/config/tokens/core.json
The scope of the changes in this pull request are to create a new formatter for `token-builder` called `json-minimal`. This generates an extremely light-weight json DTO for distribution.
* Added Docs workflow username to runner
* Removed bad package script for a non-existant workspace
* Updated the `tokens` package to use the new formatter.
=> Feat/token builder/json minimal format

packages/@momentum-design/builder/FORMATS.md, packages/@momentum-design/builder/src/assets/builder/async-utils.ts, packages/@momentum-design/builder/src/assets/builder/builder.ts, packages/@momentum-design/builder/src/assets/builder/constants.ts, packages/@momentum-design/builder/src/assets/builder/file-handler.ts, packages/@momentum-design/builder/src/assets/builder/flow.ts, packages/@momentum-design/builder/src/assets/builder/transformer.ts, packages/@momentum-design/builder/src/assets/builder/types.ts, packages/@momentum-design/builder/src/commands/definition/definition.ts, packages/@momentum-design/builder/src/commands/definition/definition.unit.test.ts, packages/@momentum-design/builder/src/models/builder/builder.ts, packages/@momentum-design/builder/src/models/builders/builders.ts, packages/@momentum-design/builder/tsconfig.json, packages/@momentum-design/icons/config/momentum.json, packages/@momentum-design/illustrations/config/momentum.json
- Changed assets builder to allow flows
- Flows are running in series, such that they can be chained in the future in the config to convert svg -> css -> scss -> font etc.
- Added async utils for running promises in series
- Added Flow class abstraction for easier use
**Note:**
To test locally, build the builder and then build the icons package. 
**Upcoming work:**
- Add renaming step
- Extend Transformer class to allow different transforms, like SVG to CSS, etc.
=> feat: added flows to assets builder

packages/@momentum-design/tokens/config/tokens/core.json
The scope of the changes in this pull request are to set the `name` property in the config object for `@momentum-design/tokens` to the proper key of `cssSelector`.
=> fix(tokens): css selector

.github/workflows/docs.yml
The scope of the changes in this pr are to add a unique hash to each docs deploy so that `git add` does not `exit 1`.
=> fix(automation): deploy docs diff

packages/@momentum-design/icons/config/momentum.json
Right now colored icons coming in have a fill on both the standard paths (black/white) and on the colored paths.
In momentum-design we do not remove the fill of colored icons so far, so that restricts consumers in color-theming also multi-colored icons.
This PR is removing the fill of paths, where the fill has the value "#0F0F0F", such that we can override that fill with theme colors in Momentum React v2.
This should also make sure only the hard coded colored parts are being kept on the svg, but not the themable colors.
=> fix: remove fill on colored icons

.github/workflows/deploy-package.yml, .github/workflows/docs.yml, .github/workflows/pull-request.yml
Adding cache-dependency-path to setup node.
I think this will fix https://github.com/momentum-design/momentum-design/actions/runs/5857942350/job/15888490025
https://github.com/momentum-design/momentum-design/actions/runs/5857942350/job/15888490025
=> fix(actions): attempt at fixing cache-dependency-path

packages/@momentum-design/automation/src/utils/execute/execute.ts, packages/@momentum-design/automation/src/utils/git/git.test.ts, packages/@momentum-design/automation/src/utils/git/git.ts
- Since there are issues with the changes made in https://github.com/momentum-design/momentum-design/pull/513, this PR will fix those issues.
- The reason for the issue was that child_process exec has a different behavior (using quotes) on Windows than on Mac. This PR addressed this by converting the pretty format to use single quotes, and after run converts the single quotes back to double quotes, such that JSON.parse works as expected.
=> revert: git changes in automation

packages/@momentum-design/animations/config/momentum.json, packages/@momentum-design/animations/package.json, yarn.lock
- This change is making sure we also export a `manifest.json` file as part of the animations package, which can be used by consumers to easier import animations in a automated process by consuming this JSON file.
- This will not change the existing animations, but only adds a new `manifest.json` file in the root.
=> feat(animations): export manifest.json of animations package

packages/@momentum-design/figma-plugin-assets-export/dist/index.js, packages/@momentum-design/figma-plugin-assets-export/src/plugin/models/component.ts
- The `exportSettingsImage` is an optional variable which is mainly used to export images in Brand Visuals Library.
- When we try to export Icons and Illustrations, there is a chance of this variable being undefined which leads to plugin failure.
- This PR will fix the issue by double checking the `exportSettingsImage` variable before we consume it.
- Plus, I've added the `dist/index.js` file which is generated via `yarn build:plugin`.
=> fix(asset): check image export settings before accepting

.gitignore
- Ignore `dist/**` directory in `figma-plugin-assets-export` package.
=> feat(ignore): add figma plugin dist dir to git ignore

.github/workflows/deploy-package.yml, .github/workflows/pull-request.yml
- The validate dependencies action does cause a runtime issue, where the wrong cache is used during CI.
- This will make sure the latest dependency update is always used for the pipeline by always using the correct cache.
=> fix(ci): remove validate dependencies to avoid cache issues

.syncpackrc, packages/@momentum-design/automation/package.json, packages/@momentum-design/builder/package.json, packages/@momentum-design/common/package.json, packages/@momentum-design/docs/package.json, packages/@momentum-design/telemetry/package.json, packages/@momentum-design/token-builder/package.json, yarn.lock
- Fix @types/node to match our used node engine version (20.15.1 -> @types/node: 20.14.9)
- Updated synpackrc config to enforce across packages
=> fix(ci): types node to match node version

package.json, packages/assets/icons/package.json, yarn.lock
- clean-css-cli is installed in root, should be installed in subpackage.
This will have no affect on the output of icons, purely development related.
=> fix(icons): clean-css-cli by moving to subpackage

packages/@momentum-design/figma-plugin-assets-export/config/figma-plugin-settings-default.json
- This PR is to update path of illustrations library in figma plugin settings json.
- This PR is a follow up of https://github.com/momentum-design/momentum-design/pull/745
- Here is the test PR created locally using these settings: https://github.com/momentum-design/momentum-design/pull/752
=> fix(json): update path in figma plugin settings json for illustrations

packages/@momentum-design/docs/astro.config.mjs, packages/@momentum-design/docs/src/components/IconTable/IconTable.tsx, packages/@momentum-design/docs/src/components/IllustrationTable/IllustrationTable.tsx
Fix Icons and Illustrations src path.
https://momentum-design.github.io/momentum-design/en/tokens/icons/ and https://momentum-design.github.io/momentum-design/en/tokens/illustrations/ are not working. This is working after this changes.
=> fix: icons and illustrations src path

packages/@momentum-design/docs/astro.config.mjs
- Fix docs page to make sure the newly implemented import of icons and illustrations works as expected
- Tested locally and works fine
- This change will not have any impact on assets like icons, illustrations etc.
=> fix(docs): docs icons & illustrations import

.github/workflows/pull-request.yml
- Simplify cache by not using runner.os / matrix.os in cache key
- Should fix issue with build
- This PR has no affect on consumables
=> ci: simplify cache by not using runner.os in cache key

packages/components/scripts/prepareForPublish.js
- Remove devDependencies and scripts from package.json before publishing components package to npm.
- Execute the prepareForPublish.js script manually to verify that it modifies package.json as intended.
- `node scripts/prepareForPublish.js`
https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-249
=> feat: remove devDependencies and scripts before publishing components package to npm

.github/mergeable.yml
- Fix label typo in mergeable
- No affect for contributables
=> ci: mergeable label typo

.github/mergeable.yml
- fix regex in title must_include, since default `regex_flag` is already set as `i` (to ignore casing)
=> fix: mergeable-regex

packages/assets/utils/package.json
- On root, when we run `yarn clean`, then its getting failed due to a failure in `utils` package for [yarn clean](https://github.com/momentum-design/momentum-design/blob/9e615782540b8a5175844fd68ffbee5866da6a1c/packages/assets/utils/package.json#L23)
- This PR will add the missing `clean:dist` script in the `utils` package.
- https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-269
=> fix(clean): add clean dist dir for utils package

.syncpackrc, config/plop/templates/add/workspace/package.json.hbs, package.json, packages/assets/utils/package.json, packages/components/package.json, packages/documentation/package.json, packages/tools/automation/package.json, packages/tools/automation/src/models/fixtures/packages.fixture.ts, packages/tools/builder/package.json, packages/tools/common/package.json, packages/tools/figma-plugins/assets-export/package.json, packages/tools/telemetry/package.json, packages/tools/token-builder/package.json
"packageManager": "yarn@3.2.4" ensures that the specified version of Yarn is used for the current project.
"engines": { "yarn": ">=3.0.0" } specifies the minimum version of Yarn required for consuming projects.
momentum-design should not dictate the the yarn version of consumers
https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-268
=> chore: do not enforce yarn version in consuming projects

.github/mergeable.yml, .github/workflows/pull-request.yml
- Currently mergeable adds labels depending on the changeset, which then triggers the pipeline another time. We do not want that.
- From now on, if the validated label has been missing and it get added after, the pipeline will not automatically run, but we have to run it manually. This will make sure that we don't run the pipeline too often on commits (commit triggers it and the label change triggered it).
=> ci: mergeable pipeline dont run on label change

.github/workflows/pull-request.yml
- Currently the validated check in the pipeline only grabs the label from the pull request event. if its not set, it should grab it from the workflow_run and label event itself as well to make sure we are actually getting the right label value (if a rerun of a workflow for example gets triggered).
=> ci: improve validated check

.github/workflows/pull-request.yml
- Problem: The PR pipeline fails randomly due to a weird error. Ex: [failure action](https://github.com/momentum-design/momentum-design/actions/runs/10683196872/job/29610843997)
- After research, we found that to run this below script, we need the necessary packages to be `build` before to run this.
- https://github.com/momentum-design/momentum-design/blob/0e45a7bf8f646476012297d8c22a0507ebfd6901/packages/components/package.json#L43
- As github workflows run parallelly, there is no guarantee that the build will execute just before this script gets started.
- This PR will fix this issue by adding a mandatory `build step` so that it will build all the needed packages to run before `playwright` runs the above step.
- Here is the successful output:
- [JIRA …
=> fix(spec): add req packages to build for test setup

packages/components/config/plop/templates/add/component/{{componentName}}.component.ts.hbs, packages/components/config/plop/templates/add/component/{{componentName}}.stories.ts.hbs, packages/components/config/storybook/main.js, packages/components/config/storybook/preview.js, packages/components/package.json, packages/components/src/components/avatar/avatar.stories.ts, packages/components/src/components/badge/badge.stories.ts, packages/components/src/components/icon/icon.stories.ts, packages/components/src/components/iconprovider/iconprovider.stories.ts, packages/components/src/components/text/text.stories.ts, packages/components/src/components/themeprovider/themeprovider.stories.ts, packages/components/src/tsdoc.json, yarn.lock
- Added storybook addon "badges"
- Defined "wip", "stable", "deprecated" badge
- Set "wip" on all of them (once we release Themeprovider, will set it to stable - separate PR)
- Updated plop script templates
=> docs: added storybook badges addon

packages/components/config/storybook/preview.js, packages/components/scripts/copyTokens.js, packages/components/src/Consumption.mdx, packages/components/src/components/themeprovider/themeprovider.component.ts, packages/components/src/components/themeprovider/themeprovider.constants.ts, packages/components/src/components/themeprovider/themeprovider.styles.ts
- Make use of the new Typography tokens in Themeprovider component (fontFamily)
- Updated storybook to include new typography tokens
- Updated Playwright copy script to include new typography tokens
- Updated Consumption.mdx 
- Removed core theme tokens from copy scripts, since only Theme tokens should be used for colors
=> fix(themeprovider): make use of typography tokens

config/esbuild/esbuild.config.js, packages/assets/utils/esbuild.config.js, packages/assets/utils/package.json, packages/assets/utils/tsconfig.json
- Modified the exports in package.json to point to the right entry
- Modified build script to build output as CJS for better compatibility
- Exporting types, since they have been missing.
=> fix: utils export, convert to cjs and exporting types

packages/components/config/playwright/public/index.html, packages/components/config/storybook/provider/themeProvider.js, packages/components/src/Consumption.mdx, packages/components/src/components/themeprovider/themeprovider.component.ts, packages/components/src/components/themeprovider/themeprovider.constants.ts
- Due to recent conversations on the Lit discord we will now move the `mds-typography` class out to the consumer to set on the root. This will make sure its present and not changing (which was an issue).
- Made that change to the component, storybook and Playwright to be reflected like that.
- Updated Consumption guide.
=> fix: move typography out of themeprovider

packages/components/src/components/icon/icon.stories.ts
- Disable all properties of icon component.
- Hide `aria-label` attribute only for "Decorative" story.
https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-380
- For decorative icon, the aria-label is hidden.
- For informative icon, the aria-label is visible:
- Disable all props for icon component.
=> fix: tech debt for icon component

packages/components/src/tsconfig.json
- Updated tsconfig in Components package to build output in ES2020
- Removing tslib by adding importHelpers: false
=> ci: moving build to es2020 instead of commonjs

packages/assets/brand-visuals/config/momentum.json
In brand visuals svgs are being processed as part of the optimize svg build step.
Change so only svgs are processed in this stage and copy pngs to a new images folder
Update manifest to handle both locations
N/A
=> build: do not process png as svg

packages/components/src/components/icon/icon.e2e-test.ts, packages/components/src/components/icon/icon.utils.ts
- Added data-name attribute to svg part of Icon to allow for better assertions while testing.
- No changes to the Icon component functionality itself.
=> fix: add icon data-name

packages/components/config/playwright/docker/playwright.docker.config.ts, packages/components/config/playwright/playwright.config.ts
- The `mdc-text` component e2e spec is getting failed due to time limit of playwright.
- This PR will fix this issue by increasing the time from 30ms to 35ms.
- NA
=> fix: increase timeout of playwright from 30 to 35ms

packages/components/src/components/icon/icon.component.ts
- This PR will add `load` and `error` event for icon component.
- When the icon gets fetched, the `load` event will be emitted.
- When the icon fetch gets failed, then the `error` event will be emitted.
- Example code:
```
<mdc-icon
...
@load="${this.handleLoad}"
@error="${this.handleError}"
...
>
</mdc-icon>
```
- These two new events will help handle the states of the icon.
https://github.com/user-attachments/assets/96eb3843-2199-4666-b45b-dc442b13970d
- https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-454
=> refactor: add custom events for icon component

packages/components/src/components/presence/presence.component.ts
1. Added activeType state to retain the previous type/class until the new icon associated with the updated type is successfully loaded.
2. Implemented handlers for the load and error events to manage the icon loading process.
3. Upon the load event, the activeType state is updated, which subsequently updates the corresponding CSS class.
https://github.com/user-attachments/assets/fa19f06e-fa96-4c1e-b489-4aed6defd019
https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-441
=> fix: add activeType to update the class only after the icon loads

packages/components/src/components/avatarbutton/avatarbutton.styles.ts, packages/components/src/components/buttonsimple/buttonsimple.styles.ts, packages/components/src/stories/FocusRing/subcomponent-focusring.styles.ts, packages/components/src/utils/styles/index.ts
- The current implementation of focus ring focus the entire element.
- In the input type components such as input, checkbox, radio, we need to focus only on a specific section of the element instead of the entire element.
- We can now add a `className` to the focus group, and the focus ring will get attached only to that specific class instead of the entire element.
>  in `XXX.component.ts` file
```
<input  class="mdc-focus-ring"/>
```
> in `XXX.styles.ts` file,
```
...hostFocusRingStyles(true);
```
- If we want the focus ring for the entire element, then we don't need to specify any classname and it will be applied to the entire element.
```
...hostFocusRingStyles();
```
https://github.com/user-attachments/assets/2dc3698f-eff9-4b8c-adac-2b4abfe24c56
- …
=> chore: update focus ring styles for specific id

packages/documentation/src/components/IllustrationTable/IllustrationTable.css, packages/documentation/src/components/IllustrationTable/IllustrationTable.tsx, packages/documentation/src/styles/theme.css
- Regular Illustrations were invisible due to black color, fixing it with invert 
- Made grid better for illustrations to change depending on size
=> docs: fix illustrations bg inverted

packages/components/src/components/text/fonts.styles.ts, packages/components/src/components/text/text.e2e-test.ts, packages/components/src/components/text/text.stories.ts
- Fixing an issue in the font styles where the default setting of text part was not correct, due to the css selector
- Fixed storybook of Text component to reflect a none set tagname correctly.
=> fix: text-fixes-default-tagname

packages/components/src/components/text/text.e2e-test.ts
Increase the timeout value for "mobile chrome" device specifically on Text component test suite.
https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-488
=> fix: custom timeout for mobile chrome device on text test cases

packages/components/config/esbuild/esbuild-e2e.config.js, packages/components/config/playwright/public/index.html, packages/components/src/components/avatarbutton/avatarbutton.component.ts, packages/components/src/components/button/button.component.ts, packages/components/src/components/formfieldwrapper/formfieldwrapper.stories.ts, packages/components/src/components/modalcontainer/modalcontainer.stories.ts, packages/components/src/index.ts
* Removed Buttonsimple, Modalcontainer and Formfieldwrapper from build bundle
* Updated their entry module for playwright to access it correctly
* Marked Modalcontainer as internal on storybook
* Removed label-info-text on Formfieldwrapper (wasn't updated in the prev PR)
https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-499
=> fix: removing internal components from build bundle

packages/tools/figma-plugins/assets-export/config/figma-plugin-settings-default.json
- Updated Figma Plugin Assets Exports Settings to match new folder structure
=> fix: figma-plugin-assets-export-settings-update

packages/components/config/playwright/public/index.html, packages/components/config/storybook/main.js, packages/components/package.json, packages/components/src/components/icon/icon.component.ts, packages/components/src/components/icon/icon.utils.ts, packages/components/src/components/iconprovider/iconprovider.component.ts, packages/components/src/components/iconprovider/iconprovider.constants.ts, packages/components/src/components/iconprovider/iconprovider.context.ts, packages/components/src/components/iconprovider/iconprovider.e2e-test.ts, packages/components/src/components/iconprovider/iconprovider.stories.ts, packages/components/src/components/iconprovider/iconprovider.stories.utils.ts, packages/components/src/components/iconprovider/iconprovider.types.ts, yarn.lock
- Allowing consumers to change the way icons are imported through the iconprovider. This allows to change the iconSet, by default when using `momentum-icons` Icons are going to be dynamically imported via JS. The already existing approach of fetching svgs from the backend is still available as before, without changes to that (and the provided caching options).
- The newly added dynamic js import requires changes in the consumers build tooling to allow for dynamic imports (there are plugins available for build tooling or built-in support).
=> fix: iconprovider consume ts icons

packages/components/config/custom-elements-manifest.config.js, packages/components/config/plop/templates/add/component/{{componentName}}.component.ts.hbs, packages/components/conventions/component-tsdoc.md, packages/components/package.json, packages/components/scripts/makeReact.js, packages/components/src/components/avatarbutton/avatarbutton.component.ts, packages/components/src/components/button/button.component.ts, packages/components/src/components/buttonsimple/buttonsimple.component.ts, packages/components/src/components/checkbox/checkbox.component.ts, packages/components/src/components/input/input.component.ts, packages/components/src/components/radio/radio.component.ts, packages/components/src/components/tab/tab.component.ts, packages/components/src/components/toggle/toggle.component.ts, packages/components/src/components/virtualizedlist/virtualizedlist.component.ts, yarn.lock
- Extended the `makeReact` script to pass in the events from the CEM to the React component
- Updating the CEM (Custom Elements Manifest) Analyzer config to pass through the event from the TS Doc
- Updated all components to specify the most commonly used events for now on them to do the mapping.
=> fix: react event passing

packages/components/src/components/buttonsimple/buttonsimple.component.ts, packages/components/src/components/checkbox/checkbox.component.ts, packages/components/src/components/input/input.component.ts, packages/components/src/components/radio/radio.component.ts, packages/components/src/components/toggle/toggle.component.ts, packages/components/src/utils/mixins/FormInternalsMixin.ts
Updated Buttonsimple to add form internals separately.
FormInternalMixin would be used only on input components.
https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-567
=> refactor: remove forminternalmixin on button

packages/assets/brand-visuals/config/momentum.json, packages/assets/brand-visuals/config/templates/lit.ts.hbs, packages/assets/icons/config/momentum.json, packages/tools/builder/src/assets/builder/transformer/lit-transformer.ts, packages/tools/builder/src/assets/builder/transformer/lit-transformer.unit.test.ts, packages/tools/builder/src/assets/builder/types.ts
- Enable builder config to export Brand Visuals as Typescript Lit Template files
- Enhanced builder tooling to support passing partName to lit transformer
- Added unit testing
**NOTE:** Brand Visual Logos are now in separate `svg` & `ts` folders, this PR might break your import of logos - when upgrading to this version, make sure to check your import paths.
=> chore: added brand visuals ts logos

packages/components/src/components/popover/popover.component.ts, packages/components/src/components/popover/popover.constants.ts, packages/components/src/components/popover/popover.stories.ts
- add a "disable-aria-expanded" attribute to the popover component
- will be used by coachmark and tooltip
- default is false, so we don't affect the normal behaviour for popover
popover is sitll wip and does not have e2e tests yet, so none have been added for this change
_Please replace this line with relevant links to the changes made in this Pull Request._
=> feat(popover): add disable-aria-expanded attribute

packages/components/src/components/popover/popover.component.ts
Fix popover cannot find the trigger element in shadow dom.
=> fix: fixing popover cannot find trigger in shadow dom

packages/components/src/components/popover/popover.component.ts
fix bug where onHide events were firing on initial render by updating `isOpenUpdated` logic
=> fix(popover): stop isOpenUpdated from running on initial render

packages/components/config/storybook/main.js
- Making sure "Example" stories are always appear on top in storybook
- No change to any component, just a fix for storybook
=> fix: storybook sort example top

packages/components/src/components/select/select.component.ts
- The new typescript version 5.8.2 is failing due to an issue with a property name in select component.
- This PR will fix this issue by updating the property name to a new name.
- Going further, we should update the current ts version from 4.8 to 5.2 as 4.8 is 3 years old.
- https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-631
=> fix: update showPopover prop to displayPopover to resolve ts issue

packages/components/src/components/tooltip/tooltip.component.ts, packages/components/src/components/tooltip/tooltip.e2e-test.ts
Pr:
Removed show arrow override from tooltip to respect the consumer intent, whether consumer wants it or not.
Link
[Ticket](https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-627)
=> fix: removed tooltip show arrow override

packages/components/src/components/button/button.component.ts
- Fix an issue where the iconname doesn't get updated to the filled version after a React component rerenders when active = true. 
- This also prevents any issues with tracking attributes, such that the iconname used for the icon itself will only be modified internally and the prefix and postfixIcon attributes are staying as intended on the button itself.
=> fix: button-active-filled-iconname

packages/documentation/CONTRIBUTING.md, packages/documentation/src/components/BrandVisualsTable/BrandVisualsTable.tsx
- The logos path for brand-visuals got affected due to the addition of typescript based files for logos.
- This PR fixes this issue by replacing the string with a req exp match.
- Additionally, I've added the steps to start the docs package locally.
- https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-653
=> docs: update docs with steps to start docs and fix logos path

packages/components/package.json
* After updating playwright version, `test:e2e:docker:update-snapshot` command was running for all the components irrespective of whether a file name was provided.
* This fix helps us get the desired result without creating any issue.
=> fix: minor change to the command

packages/components/src/components/popover/popover.component.ts, packages/components/src/components/popover/popover.stories.ts
- When there is more than 1 popover on the screen and if the user clicks on the 2nd popover trigger element then the 1st popover should be closed (if open).
- But the 1st popover is not getting closed and being added to the popover stack.
- The reason for such behaviour is due to the `visible` property of the popover being set to `true` on showPopover method which is triggering a second lifecycle update, which is causing this issue.
- Due to the events getting bubbled up, we are unable to close the popover, as the value in `this` and `popoverStack.peek()` are different and we are unable to determine the same value to pop the previous popover stack out.
- After several trial and errors, multiple ways, I've found a simple way to close the active popover when the user clicks on outside …
=> fix: resolve outside click event on popover

packages/components/src/components/dialog/dialog.component.ts, packages/components/src/components/dialog/dialog.constants.ts, packages/components/src/components/dialog/dialog.stories.ts, packages/components/src/utils/mixins/FocusTrapMixin.ts
- Allow focus trap to be set for Dialog. It should be avoided though at all costs, given that the Dialog component is a Modal Dialog. Only set this to false in case u handle the focustrap manually on the implementation side.
=> fix: dialog focustrap expose

packages/components/package.json, packages/components/prettier.config.js, yarn.lock
- Prettier doesn't support formating `.feature` files directly.
- This PR contains addition of a new plugin [prettier-plugin-gherkin](https://www.npmjs.com/package/prettier-plugin-gherkin) to format the gherkin sytanx in the .feature files.
=> fix: support prettier for feature file

packages/components/src/components/menupopover/menupopover.component.ts, packages/components/src/components/menupopover/menupopover.e2e-test.ts, packages/components/src/components/menupopover/menupopover.feature, packages/components/src/components/menupopover/menupopover.stories.ts, packages/components/src/components/popover/popover.stack.ts
- The current popover implementation doesn't allow user to click a submenu if another submenu is already open.
- Issues arise when multiple submenus are open; clicking one can inadvertently close others.
- Debugging reveals that outside clicks trigger closure of all popovers, not just the targeted ones.
- This PR fixes this issue.
- Checkout this vidcast for more info on this issue: https://app.vidcast.io/share/0df6d7f8-2a78-4eda-a75f-4c2eb8c76cf3
=> chore: add test case to handle multiple submenu mouse navigation

packages/components/src/components/select/select.component.ts, packages/components/src/components/select/select.e2e-test.ts, packages/components/src/components/select/select.stories.ts
- [Select] adding a public method on the component to allow for a stateUpdate. This is for cases where the selected attribute on passed Options changes programmatically on the outside. By firing this method the state of the Select internally will be updated.
=> fix: select add updatestate method for selected changes

packages/components/src/components/list/index.ts, packages/components/src/components/list/list.accessibility.mdx, packages/components/src/components/list/list.component.ts, packages/components/src/components/list/list.e2e-test.ts, packages/components/src/components/list/list.stories.ts, packages/components/src/components/list/list.styles.ts
**Breaking changes:**
- [List] Removed `header-text` attribute in favour of passing in `mdc-listheader` component to a slot. This will allow for higher flexibility and allows for using icons and more in list headers too - which wasn't possible before.
- [List] Removed `data-aria-label` attribute in favour of `aria-label`, since the mdc-list itself now has role='list'. This will provide higher flexibility in terms of setting aria attributes directly on the host.
**Fixes & Chore:**
- [List] Exposed parts and css properties for easier customisation
- [List] Cleaned up storybook and E2E Tests
=> fix: several fixes to list component

packages/components/src/components/select/select.component.ts
- [Select] Fix an issue where keydown events in Select nested popover are bubbling
=> fix: stop event bubbling of keydown in select popover

packages/components/LEARNINGS.md, packages/components/src/components/listitem/listitem.styles.ts, packages/components/src/components/navmenuitem/navmenuitem.styles.ts
Fixes an issue where a disabled menu item was still emitting a click event.
Suppresses click event when the menu item is disabled.
=> fix: prevent click event from emitting on disabled menu item

packages/components/src/components/input/input.types.ts, packages/components/src/index.ts
- Re-exporting input typescript types
=> fix: reexport input types

packages/components/src/components/menuitemcheckbox/menuitemcheckbox.component.ts, packages/components/src/components/menuitemcheckbox/menuitemcheckbox.e2e-test.ts, packages/components/src/components/menuitemcheckbox/menuitemcheckbox.stories.ts, packages/components/src/utils/mixins/ControlledMixin.ts
- Add 'ControlledMixin' which adds a boolean attribute 'controlled' to provide a consistent interface for controlled components.
- Add 'ControlledMixin' to MenuItemCheckbox and use controlled attribute to determine whether to toggle the checkbox on click/keyboard control
- Add tests and improve existing tests, add controlled (and soft-disabled) to story
=> fix(controlled): add controlled option for menuitemcheckbox

packages/components/src/utils/controllers/ElementStore.ts
Element store do not wait for destroy events and do not call `onStoreUpdate` after the host disconnected
=> fix(utils): element store handle host disconnection properly

packages/components/src/components/searchfield/searchfield.styles.ts
The searchfield component displays an unwanted native webkit search cancel button (X) when users hover over the input field in webkit-based browsers (Chrome, Safari, Edge).
- Added CSS rules to completely hide the webkit search cancel button using `-webkit-appearance: none` and `pointer-events: none`
=> fix(searchfield): hide webkit search cancel button on hover

package.json, yarn.lock
This PR completes the resolution of **Dependabot alert [76](https://github.com/momentum-design/momentum-design/security/dependabot/76)** by eliminating the remaining vulnerable `form-data@4.0.0` dependency.
Our previous security PR [1580](https://github.com/momentum-design/momentum-design/pull/1580) updated `jest-environment-jsdom` and `@estruyf/github-actions-reporter`, but a third dependency chain was still pulling in vulnerable form-data:
Third chain: @figma/code-connect@npm:^1.3.4 → jsdom@^24.1.3 → form-data@^4.0.0
Added yarn resolution to force all packages to use secure jsdom version:
`{
"resolutions": {
"form-data": "^4.0.4"
}
}`
We considered upgrading `@figma/code-connect` but discovered:
- **Latest version still vulnerable**: Even `@figma/code-connect@1.3.6` (latest) still uses …
=> fix: Add yarn resolution for form-data to fix vulnerability
